language: bash

sudo: required

services:
    - docker
    
before_script: 
    - chmod +x Backend/test/redis/RunRedis.sh
    - Backend/test/redis/RunRedis.sh
    - chmod +x Backend/test/redis/RunDjangoServer.sh
    - Backend/test/redis/RunDjangoServer.sh
    
jobs:
    include:
        - stage: 
          language: node_js
          node_js: '13'
          install: 
            - cd Backend 
            - npm install
            - cd ..
            - npm install mocha -g
          script: 
            - mocha Backend/test/assignment_tests.js -t 10000
            